version: '3.3'

services:
  backend:
    build: ./backend/
    container_name: backend
    depends_on:
      #- db
      - notif
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=dev.ch5k3r3kyzit.us-east-1.rds.amazonaws.com:5432
      - SPRING_DATASOURCE_USERNAME=dbadmin
      - SPRING_DATASOURCE_PASSWORD=dbadmin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FRONTEND_HOST=http://localhost
      - SERVICE_NOTIFICATION_HOST=http://notif:8081
  notif:
    build: ./notification-service/
    container_name: notif
    ports:
      - "8081:8081"
  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "80:80"
  # db:
  #   image: 'postgres:13.1-alpine'
  #   container_name: db
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=ladder
  #   expose:
  #     - 5432
