apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ladder
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      project: backend
  template:
    metadata:
      labels:
        project: backend # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: backend
          image: 498561179155.dkr.ecr.us-east-1.amazonaws.com/practice:backend_6d05edf5bb7da81212cf123b0e2f86a076d7c76d
          daemon: true
          ports:
            - containerPort: 8080
