apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ladder
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      project: backend
  template:
    metadata:
      labels:
        project: backend # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: backend
          image: 498561179155.dkr.ecr.us-east-1.amazonaws.com/practice:backend_29b654e933a3c0e74ee27e9c1371cb549e4d1136
          daemon: true
          ports:
            - containerPort: 8080
