apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ladder
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      project: backend
  template:
    metadata:
      labels:
        project: backend # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: backend
          image: 498561179155.dkr.ecr.us-east-1.amazonaws.com/practice:backend_274e07847da60ea5a58bea10d1ad4cee51489006
          ports:
            - containerPort: 8080
