apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ladder
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      project: frontend
  template:
    metadata:
      labels:
        project: frontend # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: frontend
          image: 498561179155.dkr.ecr.us-east-1.amazonaws.com/practice:frontend_317b25372b40783086164b3ba917c267fdc5596a
          ports:
            - containerPort: 80
