apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ladder
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      project: frontend
  template:
    metadata:
      labels:
        project: frontend # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: frontend
          image: 498561179155.dkr.ecr.us-east-1.amazonaws.com/practice:frontend_3b27d2246c523f4e50ffc79690c1b3237caa4317
          ports:
            - containerPort: 80
