apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-ladder
  labels:
    app: notif
spec:
  selector:
    matchLabels:
      project: notif
  template:
    metadata:
      labels:
        project: notif # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: notif
          image: 498561179155.dkr.ecr.us-east-1.amazonaws.com/practice:notif_317b25372b40783086164b3ba917c267fdc5596a
          ports:
            - containerPort: 8081
