apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-ladder
  labels:
    app: notif
spec:
  selector:
    matchLabels:
      project: notif
  template:
    metadata:
      labels:
        project: notif # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: notif
          image: 498561179155.dkr.ecr.us-east-1.amazonaws.com/practice:notif_55d64516a50420aafb1c84f61c9d8b48b9bd6ca1
          ports:
            - containerPort: 8081
